#!/usr/bin/env python3
"""
Smart Alert System Module
ML-based anomaly alerts with email, Slack, and popup notifications
"""

import smtplib
import logging
import json
import threading
import time
import queue
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests

# Import our data structures
import sys
project_root = Path(__file__).parent
sys.path.append(str(project_root))
from anomaly import AnomalyScore


@dataclass
class AlertRule:
    """Alert rule configuration"""
    name: str
    anomaly_score_threshold: float
    confidence_threshold: float
    satellite_filter: Optional[List[str]]
    anomaly_types: Optional[List[str]]
    cooldown_minutes: int
    enabled: bool
    notification_channels: List[str]  # ['email', 'slack', 'popup']


@dataclass
class AlertEvent:
    """Alert event data"""
    id: str
    timestamp: datetime
    satellite_id: str
    anomaly_score: AnomalyScore
    rule_name: str
    severity: str
    message: str
    acknowledged: bool
    resolved: bool


class EmailNotifier:
    """Email notification handler"""
    
    def __init__(self, smtp_server: str = "smtp.gmail.com", smtp_port: int = 587):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.logger = logging.getLogger(__name__)
        self.enabled = False
        self.username = ""
        self.password = ""
        self.from_email = ""
        self.to_emails = []
        
    def configure(self, username: str, password: str, from_email: str, to_emails: List[str]):
        """Configure email settings"""
        self.username = username
        self.password = password
        self.from_email = from_email
        self.to_emails = to_emails
        self.enabled = True
        self.logger.info("Email notifications configured")
        
    def send_alert(self, alert: AlertEvent) -> bool:
        """Send email alert"""
        if not self.enabled:
            self.logger.warning("Email notifications not configured")
            return False
            
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.from_email
            msg['To'] = ', '.join(self.to_emails)
            msg['Subject'] = f"🚨 Telemetry Alert: {alert.severity} - {alert.satellite_id}"
            
            # Create HTML body
            body = f"""
            <html>
            <body>
                <h2>🛰️ Satellite Telemetry Alert</h2>
                
                <div style="background-color: #f8f9fa; padding: 10px; border-radius: 5px;">
                    <p><strong>Alert ID:</strong> {alert.id}</p>
                    <p><strong>Timestamp:</strong> {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
                    <p><strong>Satellite:</strong> {alert.satellite_id}</p>
                    <p><strong>Severity:</strong> <span style="color: red;">{alert.severity}</span></p>
                    <p><strong>Rule:</strong> {alert.rule_name}</p>
                </div>
                
                <h3>Anomaly Details</h3>
                <div style="background-color: #fff3cd; padding: 10px; border-radius: 5px;">
                    <p><strong>Anomaly Type:</strong> {alert.anomaly_score.anomaly_type}</p>
                    <p><strong>Combined Score:</strong> {alert.anomaly_score.combined_score:.3f}</p>
                    <p><strong>Confidence:</strong> {alert.anomaly_score.confidence:.3f}</p>
                    <p><strong>Isolation Forest Score:</strong> {alert.anomaly_score.isolation_forest_score:.3f}</p>
                    <p><strong>Autoencoder Score:</strong> {alert.anomaly_score.autoencoder_score:.3f}</p>
                    <p><strong>LSTM Score:</strong> {alert.anomaly_score.lstm_score:.3f}</p>
                </div>
                
                <h3>Message</h3>
                <p>{alert.message}</p>
                
                <hr>
                <p><small>Generated by Telemetry Monitor System</small></p>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(body, 'html'))
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)
            
            self.logger.info(f"Email alert sent for {alert.satellite_id}")
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to send email alert: {e}")
            return False


class SlackNotifier:
    """Slack notification handler"""
    
    def __init__(self):
        self.webhook_url = ""
        self.enabled = False
        self.logger = logging.getLogger(__name__)
        
    def configure(self, webhook_url: str):
        """Configure Slack webhook"""
        self.webhook_url = webhook_url
        self.enabled = True
        self.logger.info("Slack notifications configured")
        
    def send_alert(self, alert: AlertEvent) -> bool:
        """Send Slack alert"""
        if not self.enabled:
            self.logger.warning("Slack notifications not configured")
            return False
            
        try:
            # Create Slack message
            severity_emoji = {
                'LOW': '🟡',
                'MEDIUM': '🟠', 
                'HIGH': '🔴',
                'CRITICAL': '🚨'
            }
            
            emoji = severity_emoji.get(alert.severity, '⚠️')
            
            message = {
                "text": f"{emoji} Telemetry Alert: {alert.severity}",
                "attachments": [
                    {
                        "color": "danger" if alert.severity in ['HIGH', 'CRITICAL'] else "warning",
                        "fields": [
                            {"title": "Satellite", "value": alert.satellite_id, "short": True},
                            {"title": "Anomaly Type", "value": alert.anomaly_score.anomaly_type, "short": True},
                            {"title": "Score", "value": f"{alert.anomaly_score.combined_score:.3f}", "short": True},
                            {"title": "Confidence", "value": f"{alert.anomaly_score.confidence:.3f}", "short": True},
                            {"title": "Time", "value": alert.timestamp.strftime('%Y-%m-%d %H:%M:%S'), "short": True},
                            {"title": "Rule", "value": alert.rule_name, "short": True}
                        ],
                        "text": alert.message,
                        "footer": "Telemetry Monitor",
                        "ts": int(alert.timestamp.timestamp())
                    }
                ]
            }
            
            # Send to Slack
            response = requests.post(self.webhook_url, json=message, timeout=10)
            response.raise_for_status()
            
            self.logger.info(f"Slack alert sent for {alert.satellite_id}")
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to send Slack alert: {e}")
            return False


class PopupNotifier:
    """Desktop popup notification handler"""
    
    def __init__(self):
        self.enabled = True
        self.logger = logging.getLogger(__name__)
        self.popup_queue = queue.Queue()
        
    def send_alert(self, alert: AlertEvent) -> bool:
        """Send popup alert (queue for GUI display)"""
        try:
            self.popup_queue.put(alert)
            self.logger.info(f"Popup alert queued for {alert.satellite_id}")
            return True
        except Exception as e:
            self.logger.error(f"Failed to queue popup alert: {e}")
            return False
    
    def get_pending_alerts(self) -> List[AlertEvent]:
        """Get pending popup alerts"""
        alerts = []
        try:
            while not self.popup_queue.empty():
                alerts.append(self.popup_queue.get_nowait())
        except queue.Empty:
            pass
        return alerts


class SmartAlertSystem:
    """Main alert system with ML-based anomaly detection"""
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        
        # Notification handlers
        self.email_notifier = EmailNotifier()
        self.slack_notifier = SlackNotifier()
        self.popup_notifier = PopupNotifier()
        
        # Alert rules
        self.alert_rules = []
        self.load_default_rules()
        
        # Alert history
        self.alert_history = []
        self.alert_cooldowns = {}  # Track cooldown periods
        
        # Alert processing
        self.alert_queue = queue.Queue()
        self.is_running = False
        self.processing_thread = None
        
        # Configuration
        self.config_file = project_root / "data" / "alert_config.json"
        self.load_configuration()
        
    def load_default_rules(self):
        """Load default alert rules"""
        self.alert_rules = [
            AlertRule(
                name="Critical ML Anomaly",
                anomaly_score_threshold=0.8,
                confidence_threshold=0.7,
                satellite_filter=None,
                anomaly_types=None,
                cooldown_minutes=5,
                enabled=True,
                notification_channels=['email', 'slack', 'popup']
            ),
            AlertRule(
                name="High ML Anomaly",
                anomaly_score_threshold=0.6,
                confidence_threshold=0.6,
                satellite_filter=None,
                anomaly_types=None,
                cooldown_minutes=10,
                enabled=True,
                notification_channels=['popup']
            ),
            AlertRule(
                name="Temporal Anomaly",
                anomaly_score_threshold=0.5,
                confidence_threshold=0.5,
                satellite_filter=None,
                anomaly_types=['temporal_anomaly'],
                cooldown_minutes=15,
                enabled=True,
                notification_channels=['popup', 'slack']
            )
        ]
        
    def load_configuration(self):
        """Load alert configuration from file"""
        try:
            if self.config_file.exists():
                with open(self.config_file, 'r') as f:
                    config = json.load(f)
                
                # Load email config
                email_config = config.get('email', {})
                if email_config.get('enabled', False):
                    self.email_notifier.configure(
                        username=email_config.get('username', ''),
                        password=email_config.get('password', ''),
                        from_email=email_config.get('from_email', ''),
                        to_emails=email_config.get('to_emails', [])
                    )
                
                # Load Slack config
                slack_config = config.get('slack', {})
                if slack_config.get('enabled', False):
                    self.slack_notifier.configure(
                        webhook_url=slack_config.get('webhook_url', '')
                    )
                
                self.logger.info("Alert configuration loaded")
                
        except Exception as e:
            self.logger.error(f"Failed to load alert configuration: {e}")
    
    def save_configuration(self, email_config: Dict = None, slack_config: Dict = None):
        """Save alert configuration to file"""
        try:
            config = {}
            
            if email_config:
                config['email'] = email_config
                
            if slack_config:
                config['slack'] = slack_config
            
            # Ensure data directory exists
            self.config_file.parent.mkdir(exist_ok=True)
            
            with open(self.config_file, 'w') as f:
                json.dump(config, f, indent=2)
            
            self.logger.info("Alert configuration saved")
            
        except Exception as e:
            self.logger.error(f"Failed to save alert configuration: {e}")
    
    def start(self):
        """Start the alert processing system"""
        if not self.is_running:
            self.is_running = True
            self.processing_thread = threading.Thread(target=self._alert_processing_loop, daemon=True)
            self.processing_thread.start()
            self.logger.info("Smart alert system started")
    
    def stop(self):
        """Stop the alert processing system"""
        self.is_running = False
        if self.processing_thread and self.processing_thread.is_alive():
            self.processing_thread.join(timeout=5)
        self.logger.info("Smart alert system stopped")
    
    def process_anomaly_score(self, anomaly_score: AnomalyScore):
        """Process anomaly score and generate alerts if needed"""
        try:
            # Check each rule
            for rule in self.alert_rules:
                if not rule.enabled:
                    continue
                
                # Check if anomaly meets rule criteria
                if self._matches_rule(anomaly_score, rule):
                    # Check cooldown period
                    cooldown_key = f"{rule.name}_{anomaly_score.satellite_id}"
                    last_alert_time = self.alert_cooldowns.get(cooldown_key)
                    
                    if last_alert_time:
                        time_diff = datetime.now() - last_alert_time
                        if time_diff.total_seconds() < rule.cooldown_minutes * 60:
                            continue  # Still in cooldown period
                    
                    # Create alert event
                    alert = self._create_alert_event(anomaly_score, rule)
                    
                    # Queue for processing
                    self.alert_queue.put(alert)
                    
                    # Update cooldown
                    self.alert_cooldowns[cooldown_key] = datetime.now()
                    
        except Exception as e:
            self.logger.error(f"Failed to process anomaly score: {e}")
    
    def _matches_rule(self, anomaly_score: AnomalyScore, rule: AlertRule) -> bool:
        """Check if anomaly score matches alert rule"""
        # Check score threshold
        if anomaly_score.combined_score < rule.anomaly_score_threshold:
            return False
        
        # Check confidence threshold
        if anomaly_score.confidence < rule.confidence_threshold:
            return False
        
        # Check satellite filter
        if rule.satellite_filter and anomaly_score.satellite_id not in rule.satellite_filter:
            return False
        
        # Check anomaly type filter
        if rule.anomaly_types and anomaly_score.anomaly_type not in rule.anomaly_types:
            return False
        
        return True
    
    def _create_alert_event(self, anomaly_score: AnomalyScore, rule: AlertRule) -> AlertEvent:
        """Create alert event from anomaly score and rule"""
        # Determine severity based on score
        if anomaly_score.combined_score >= 0.9:
            severity = "CRITICAL"
        elif anomaly_score.combined_score >= 0.8:
            severity = "HIGH"
        elif anomaly_score.combined_score >= 0.6:
            severity = "MEDIUM"
        else:
            severity = "LOW"
        
        # Create message
        message = f"ML anomaly detected on {anomaly_score.satellite_id}: {anomaly_score.anomaly_type} " \
                 f"(Score: {anomaly_score.combined_score:.3f}, Confidence: {anomaly_score.confidence:.3f})"
        
        # Generate unique ID
        alert_id = f"{anomaly_score.satellite_id}_{int(anomaly_score.timestamp.timestamp())}"
        
        return AlertEvent(
            id=alert_id,
            timestamp=anomaly_score.timestamp,
            satellite_id=anomaly_score.satellite_id,
            anomaly_score=anomaly_score,
            rule_name=rule.name,
            severity=severity,
            message=message,
            acknowledged=False,
            resolved=False
        )
    
    def _alert_processing_loop(self):
        """Main alert processing loop"""
        self.logger.info("Alert processing loop started")
        
        while self.is_running:
            try:
                # Get alert from queue
                try:
                    alert = self.alert_queue.get(timeout=1.0)
                except queue.Empty:
                    continue
                
                # Process alert
                self._send_notifications(alert)
                
                # Add to history
                self.alert_history.append(alert)
                
                # Keep only last 1000 alerts
                if len(self.alert_history) > 1000:
                    self.alert_history = self.alert_history[-1000:]
                
                # Mark task as done
                self.alert_queue.task_done()
                
            except Exception as e:
                self.logger.error(f"Error in alert processing loop: {e}")
                time.sleep(0.1)
        
        self.logger.info("Alert processing loop ended")
    
    def _send_notifications(self, alert: AlertEvent):
        """Send notifications for alert event"""
        rule = next((r for r in self.alert_rules if r.name == alert.rule_name), None)
        if not rule:
            return
        
        # Send notifications based on rule configuration
        for channel in rule.notification_channels:
            try:
                if channel == 'email':
                    self.email_notifier.send_alert(alert)
                elif channel == 'slack':
                    self.slack_notifier.send_alert(alert)
                elif channel == 'popup':
                    self.popup_notifier.send_alert(alert)
            except Exception as e:
                self.logger.error(f"Failed to send {channel} notification: {e}")
    
    def get_pending_popup_alerts(self) -> List[AlertEvent]:
        """Get pending popup alerts"""
        return self.popup_notifier.get_pending_alerts()
    
    def get_alert_history(self, limit: int = 50) -> List[AlertEvent]:
        """Get recent alert history"""
        return self.alert_history[-limit:] if len(self.alert_history) > limit else self.alert_history
    
    def acknowledge_alert(self, alert_id: str):
        """Acknowledge an alert"""
        for alert in self.alert_history:
            if alert.id == alert_id:
                alert.acknowledged = True
                self.logger.info(f"Alert {alert_id} acknowledged")
                break
    
    def resolve_alert(self, alert_id: str):
        """Resolve an alert"""
        for alert in self.alert_history:
            if alert.id == alert_id:
                alert.resolved = True
                self.logger.info(f"Alert {alert_id} resolved")
                break
    
    def get_stats(self) -> Dict[str, Any]:
        """Get alert system statistics"""
        active_alerts = [a for a in self.alert_history if not a.resolved]
        unacknowledged_alerts = [a for a in active_alerts if not a.acknowledged]
        
        return {
            'total_alerts': len(self.alert_history),
            'active_alerts': len(active_alerts),
            'unacknowledged_alerts': len(unacknowledged_alerts),
            'enabled_rules': len([r for r in self.alert_rules if r.enabled]),
            'queue_size': self.alert_queue.qsize(),
            'is_running': self.is_running
        }


# Global alert system instance
_alert_system = None

def get_alert_system() -> SmartAlertSystem:
    """Get global alert system instance"""
    global _alert_system
    if _alert_system is None:
        _alert_system = SmartAlertSystem()
    return _alert_system


if __name__ == "__main__":
    # Test the alert system
    logging.basicConfig(level=logging.INFO)
    
    alert_system = SmartAlertSystem()
    
    print("Testing Smart Alert System...")
    
    try:
        alert_system.start()
        print("Alert system started successfully!")
        
        # Test would require actual anomaly scores
        # This is just a placeholder
        
        time.sleep(2)
        alert_system.stop()
        print("Alert system test completed!")
        
    except Exception as e:
        print(f"Test failed: {e}")